---
services:
  node-exporter:
    image: "prom/node-exporter:master"
    container_name: "node-exporter"
    hostname: "CHANGEME"
    restart: "unless-stopped"
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
      - "--collector.netclass.ignored-devices=^(veth.*|docker.*|br-.*|vmnet.*|lo)$$"
    ports:
      - "9100:9100"
    networks:
      node-exporter-network:
        ipv4_address: "172.88.91.254"
networks:
  node-exporter-network:
    driver: "bridge"
    enable_ipv6: false
    ipam:
      config:
        - subnet: "172.88.91.0/24"
...
