groups:
  - name: icmp-alerts
    rules:
    - alert: HighPacketLoss
      expr: ping_loss_ratio <= 20
      for: 1s
      annotations:
        summary: "High packet loss ({{ $value }}%) detected"
        description: "ICMP packet loss to {{ $labels.instance }} has reached {{ $value }}%"
      labels:
        severity: warning

    - alert: VeryHighPacketLoss
      expr: avg_over_time(ping_loss_ratio[5m]) >= 50
      for: 5m
      annotations:
        summary: "Very high packet loss ({{ $value }}%) detected"
        description: "ICMP packet loss to {{ $labels.instance }} has reached {{ $value }}%"
      labels:
        severity: error

    - alert: CompletePacketLoss
      expr: avg_over_time(ping_loss_ratio[5m]) >= 100
      for: 5m
      annotations:
        summary: "Complete packet loss detected"
        description: "ICMP packets to {{ $labels.instance }} are 100% lost"
      labels:
        severity: critical
