---
groups:
  - name: "icmp-alerts"
    rules:
      - alert: "HighPacketLoss"
        expr: "avg_over_time(ping_loss_ratio[1m]) >= 20"
        for: "1m"
        annotations:
          summary: "High packet loss ({{ $value }}%) detected"
          description: |
            ICMP packet loss to {{ $labels.target }} has reached {{ $value }}%

        labels:
          severity: "warning"

      - alert: "VeryHighPacketLoss"
        expr: "avg_over_time(ping_loss_ratio[1m]) >= 50"
        for: "1m"
        annotations:
          summary: "Very high packet loss ({{ $value }}%) detected"
          description: |
            "ICMP packet loss to {{ $labels.target }} has reached {{ $value }}%"
        labels:
          severity: "error"

      - alert: "CompletePacketLoss"
        expr: "avg_over_time(ping_loss_ratio[1m]) >= 100"
        for: "1m"
        annotations:
          summary: "Complete packet loss detected"
          description: "ICMP packets to {{ $labels.target }} are 100% lost"
        labels:
          severity: "critical"
...
