global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'telegram-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'telegram-notifications'
      repeat_interval: 1h
    - match:
        severity: error
      receiver: 'telegram-notifications'
      repeat_interval: 2h
    - match:
        severity: warning
      receiver: 'telegram-notifications'
      repeat_interval: 4h

receivers:
  - name: 'telegram-notifications'
    telegram_configs:
    - bot_token_file: '/etc/alertmanager/tgtoken'
      chat_id: <YOUR_CHAT_ID>
      parse_mode: 'HTML'
      message: |
        🚨 <b>{{ .Status | toUpper }}</b>
        <b>Alert:</b> {{ .CommonAnnotations.summary }}
        <b>Severity:</b> {{ .CommonLabels.severity }}
        <b>Instance:</b> {{ .CommonLabels.instance }}
        <b>Details:</b> {{ .CommonAnnotations.description }}
        <b>Value:</b> {{ .CommonAnnotations.value }}