---
services:
  grafana:
    image: "grafana/grafana-enterprise:main-ubuntu"
    container_name: "grafana"
    restart: "unless-stopped"
    labels: ["com.centurylinklabs.watchtower.scope=mainwatchtower"]
    ports:
      - "0.0.0.0:41488:3000"
    volumes:
      - "grafana-storage:/var/lib/grafana"
      - "./grafana.ini:/etc/grafana/grafana.ini"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    secrets:
      - "grafana_secrets"
    networks:
      grafana-main:
        ipv4_address: "172.88.1.254"
  clickhouse:
    image: "clickhouse/clickhouse-server:25.6-alpine"
    container_name: "clickhouse-grafana"
    ports:
      - "0.0.0.0:8123:8123"
      - "0.0.0.0:57308:8443"
      - "0.0.0.0:30721:9000"
    volumes:
      - "clickhouse-data:/var/lib/clickhouse:rw"
      - "./clickhouse_on_startup.sql:/docker-entrypoint-initdb.d/init_db.sql:ro"
      - "./clickhouse.xml:/etc/clickhouse-server/config.xml:ro"
    environment:
      CLICKHOUSE_DB: "${CLICKHOUSE_DB}"
      CLICKHOUSE_USER: "${CLICKHOUSE_USER}"
      CLICKHOUSE_PASSWORD: "${CLICKHOUSE_PASSWORD}"
    networks:
      grafana-main:
        ipv4_address: "172.88.1.252"

  ping_exporter:
    image: "czerwonk/ping_exporter:latest"
    labels: ["com.centurylinklabs.watchtower.scope=mainwatchtower"]
    container_name: "ping_exporter"
    hostname: "ping_exporter"
    restart: "unless-stopped"
    expose:
      - "9427"
    volumes:
      - "./ping_exporter.yml:/config/config.yml:ro"
    networks:
      nginx_pingers:
        ipv4_address: "172.89.1.251"

  prometheus:
    image: "prom/prometheus:latest"
    labels: ["com.centurylinklabs.watchtower.scope=mainwatchtower"]
    container_name: "prometheus"
    restart: "unless-stopped"
    expose:
      - "9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
      - "--enable-feature=remote-write-receiver"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "./alert_rules.yml:/etc/prometheus/alert_rules.yml:ro"
    networks:
      nginx_pingers:
        ipv4_address: "172.89.1.253"
      grafana-main:
        ipv4_address: "172.88.1.253"
      node-exporter-network:
        ipv4_address: "172.90.91.253"

  watchtower-main:
    image: "containrrr/watchtower:latest"
    container_name: "watchtower-main"
    restart: "unless-stopped"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: "--scope mainwatchtower"
    labels: ["com.centurylinklabs.watchtower.scope=mainwatchtower"]
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: "86400"
      WATCHTOWER_NOTIFICATIONS_LEVEL: "info"
      WATCHTOWER_NOTIFICATION_TEMPLATE: >-
        '{{if .}}{"chat_id": "your_chat_id",
        "message_thread_id": 13,
        "parse_mode": "HTML",
        "text": "{{range .}}{{.Message}}\n{{end}}"}{{end}}'
      WATCHTOWER_NOTIFICATION_URL: >-
        "generic://api.telegram.org/bot<your_bot_token>/sendMessage"

  node-exporter:
    image: "prom/node-exporter:master"
    container_name: "node-exporter"
    hostname: "Grafana"
    labels: ["com.centurylinklabs.watchtower.scope=mainwatchtower"]
    restart: "unless-stopped"
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
      - "--collector.netclass.ignored-devices=^(veth.*|docker.*|br-.*|vmnet.*|lo)$$"
    expose:
      - "9100"
    networks:
      node-exporter-network:
        ipv4_address: "172.90.91.254"

volumes:
  grafana-storage: {}
  clickhouse-data: {}

secrets:
  grafana_secrets:
    file: "grafana.ini"

networks:
  grafana-main:
    driver: "bridge"
    name: "grafana-main"
    enable_ipv6: false
    ipam:
      config:
        - subnet: "172.88.1.0/24"

  nginx_pingers:
    driver: "bridge"
    name: "blackbox-prometheus-nginx"
    enable_ipv6: false
    ipam:
      config:
        - subnet: "172.89.1.0/24"

  node-exporter-network:
    driver: "bridge"
    name: "node-exporter-network"
    enable_ipv6: false
    ipam:
      config:
        - subnet: "172.90.91.0/24"
...
