---
global:
  scrape_interval: "20s"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: "ping_exporter"
    scrape_interval: "5s"
    honor_labels: true
    scheme: "http"
    static_configs:
      - targets:
        - "ping_exporter:9427"

    metric_relabel_configs:
        - source_labels: [target]
          regex: "172.89.1.253"
          target_label: "name"
          replacement: "prometheus"
        - source_labels: [target]
          regex: "172.89.1.253"
          target_label: "group"
          replacement: "internal"
...
