---
global:
  scrape_interval: "20s"

scrape_configs:
  - job_name: "ping_exporter"
    scrape_interval: "5s"
    honor_labels: true
    scheme: "http"
    static_configs:
      - targets:
        - "ping_exporter:9427"

...
