---
global:
  scrape_interval: "20s"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

groups:
- name: icmp-alerts
  rules:
  - alert: HighPacketLoss
    expr: ping_loss_ratio <= 20
    for: 1s
    annotations:
      summary: "High packet loss ({{ $value }}%) detected"
      description: "ICMP packet loss to {{ $labels.instance }} has reached {{ $value }}%"
    labels:
      severity: warning

  - alert: VeryHighPacketLoss
    expr: avg_over_time(ping_loss_ratio[5m]) >= 50
    for: 5m
    annotations:
      summary: "Very high packet loss ({{ $value }}%) detected"
      description: "ICMP packet loss to {{ $labels.instance }} has reached {{ $value }}%"
    labels:
      severity: error

  - alert: CompletePacketLoss
    expr: avg_over_time(ping_loss_ratio[5m]) >= 100
    for: 5m
    annotations:
      summary: "Complete packet loss detected"
      description: "ICMP packets to {{ $labels.instance }} are 100% lost"
    labels:
      severity: critical

scrape_configs:
  - job_name: "ping_exporter"
    scrape_interval: "5s"
    honor_labels: true
    scheme: "http"
    static_configs:
      - targets:
        - "ping_exporter:9427"

    metric_relabel_configs:
        - source_labels: [target]
          regex: "172.89.1.253"
          target_label: "name"
          replacement: "prometheus"
        - source_labels: [target]
          regex: "172.89.1.253"
          target_label: "group"
          replacement: "internal"
...
