groups:
- name: icmp_loss_alerts
  rules:
  - alert: ICMPPacketLossCritical
    expr: ping_percent_packet_loss >= 100
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "ICMP 100% Packet Loss Detected"
      description: "Complete packet loss detected on {{ $labels.instance }}"
      value: "{{ $value }}% packet loss"

  - alert: ICMPPacketLossError
    expr: ping_percent_packet_loss >= 50 and ping_percent_packet_loss < 100
    for: 5m
    labels:
      severity: error
    annotations:
      summary: "ICMP High Packet Loss Detected"
      description: "High packet loss detected on {{ $labels.instance }}"
      value: "{{ $value }}% packet loss"

  - alert: ICMPPacketLossWarning
    expr: ping_percent_packet_loss >= 20 and ping_percent_packet_loss < 50
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "ICMP Moderate Packet Loss Detected"
      description: "Moderate packet loss detected on {{ $labels.instance }}"
      value: "{{ $value }}% packet loss"