---
global:
  scrape_interval: "20s"

scrape_configs:
  - job_name: "ping_exporter"
    scrape_interval: "5s"
    honor_lables: true
    scheme: "http"
    static_configs:
      - targets:
        - "ping_exporter:9427"

    relabel_configs:
      - source_labels: ["__address__"]
        target_label: "__param_target"
      - source_labels: ["__param_target"]
        target_label: "instance"
      - target_label: "__address__"
        replacement: "ping_exporter:9427"  # Address of the Ping Exporter
...
