name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule: 
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
        - uses: actions/checkout@v4
    
        - name: Build and start containers
          run: |
            for file in $(find . -name "docker-compose.yml"); do
                echo "Starting compose file: $file"
                docker compose -f $file up -d
            done
        
        - name: Check running containers
          run: docker ps
        
        - name: Stop containers
          if: always()
          run: |
            for file in $(find . -name "docker-compose.yml"); do
              echo "Stopping containers from: $file"
              docker compose -f $file down
            done
  ymllinter:
    name: yamllint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yamllint
        run: |
          pip install yamllint

      - name: YAML Lint
        run: |
                    find ./compose-files -type f \( -name "*.yml" -o -name "*.yaml" \) -exec yamllint -c .yamllint {} \;          

      - name: Docker Compose Lint
        run: |
          for file in $(find . -name "compose*.yml"); do
            echo "Linting $file..."
            docker compose -f $file config
          done
