name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
        - uses: actions/checkout@v4
    
        - name: Build and start containers
          run: |
            for file in $(find . -name "docker-compose.yml"); do
                echo "Starting compose file: $file"
                docker compose -f $file up -d
            done
        
        - name: Check running containers
          run: docker ps
        
        - name: Stop containers
          if: always()
          run: |
            for file in $(find . -name "docker-compose.yml"); do
              echo "Stopping containers from: $file"
              docker compose -f $file down
            done